./initracer.js --site walmart.com --url http://www.walmart.com/ $@
./initracer.js --site exxon.com --url https://www.exxon.com/ $@
./initracer.js --site chevron.com --url https://www.chevron.com/ $@
./initracer.js --site berkshirehathaway.com --url http://berkshirehathaway.com/ $@
./initracer.js --site apple.com --url http://www.apple.com/ $@
./initracer.js --site gm.com --url http://www.gm.com/index.html $@
./initracer.js --site phillips66.com --url http://www.phillips66.com/EN/Pages/index.aspx $@
./initracer.js --site ge.com --url http://www.ge.com/ $@
./initracer.js --site ford.com --url http://www.ford.com/ $@
./initracer.js --site cvshealth.com --url https://www.cvshealth.com/ $@
./initracer.js --site mckesson.com --url http://www.mckesson.com/ $@
./initracer.js --site att.com --url https://www.att.com/ $@
./initracer.js --site valero.com --url https://www.valero.com/en-us $@
./initracer.js --site unitedhealthgroup.com --url http://www.unitedhealthgroup.com/ $@
./initracer.js --site verizonwireless.com --url http://www.verizonwireless.com/ $@
./initracer.js --site amerisourcebergen.com --url http://www.amerisourcebergen.com/abcnew/ $@
./initracer.js --site fanniemae.com --url http://www.fanniemae.com/portal/index.html $@
./initracer.js --site costco.com --url http://www.costco.com/ $@
./initracer.js --site hp.com --url http://www.hp.com/ $@
./initracer.js --site kroger.com --url https://www.kroger.com/ $@
./initracer.js --site chase.com --url https://www.chase.com/ $@
./initracer.js --site express-scripts.com --url https://www.express-scripts.com/index.html $@
./initracer.js --site bankofamerica.com --url https://www.bankofamerica.com/ $@
./initracer.js --site ibm.com --url http://www.ibm.com/us-en/ $@
./initracer.js --site marathonpetroleum.com --url http://www.marathonpetroleum.com/ $@
./initracer.js --site cardinalhealth.com --url http://www.cardinalhealth.com/en.html $@
./initracer.js --site boeing.com --url http://www.boeing.com/ $@
./initracer.js --site citigroup.com --url http://www.citigroup.com/citi/ $@
./initracer.js --site amazon.com --url http://www.amazon.com/ $@
./initracer.js --site wellsfargo.com --url https://www.wellsfargo.com/ $@
./initracer.js --site microsoft.com --url https://www.microsoft.com/en-us/ $@
./initracer.js --site us.pg.com --url http://us.pg.com/ $@
./initracer.js --site homedepot.com --url http://www.homedepot.com/ $@
./initracer.js --site adm.com --url http://www.adm.com/en-US/Pages/default.aspx $@
./initracer.js --site walgreens.com --url http://www.walgreens.com/ $@
./initracer.js --site target.com --url http://www.target.com/ $@
./initracer.js --site jnj.com --url http://www.jnj.com/ $@
./initracer.js --site anthem.com --url https://www.anthem.com/health-insurance/home/overview $@
./initracer.js --site metlife.com --url https://www.metlife.com/ $@
./initracer.js --site abc.xyz --url https://abc.xyz/ $@
./initracer.js --site statefarm.com --url https://www.statefarm.com/ $@
./initracer.js --site freddiemac.com --url http://www.freddiemac.com/ $@
./initracer.js --site xfinity.com --url http://www.xfinity.com/ $@
./initracer.js --site pepsico.com --url http://www.pepsico.com/ $@
./initracer.js --site utc.com --url http://www.utc.com/Pages/Home.aspx $@
./initracer.js --site aig.com --url http://www.aig.com/home_3171_411330.html $@
./initracer.js --site ups.com --url https://www.ups.com/content/us/en/index.jsx $@
./initracer.js --site dow.com --url http://www.dow.com/ $@
./initracer.js --site aetna.com --url https://www.aetna.com/index.html $@
./initracer.js --site lowes.com --url http://www.lowes.com/ $@
./initracer.js --site conocophillips.com --url http://www.conocophillips.com/Pages/default.aspx $@
./initracer.js --site intel.com --url http://www.intel.com/content/www/us/en/homepage.html $@
./initracer.js --site energytransfer.com --url http://www.energytransfer.com/ $@
./initracer.js --site cat.com --url http://www.cat.com/en_US.html $@
./initracer.js --site prudential.com --url https://www.prudential.com/personal $@
./initracer.js --site pfizer.com --url http://www.pfizer.com/ $@
./initracer.js --site disney.com --url http://disney.com/ $@
./initracer.js --site humana.com --url https://www.humana.com/ $@
./initracer.js --site enterpriseproducts.com --url http://www.enterpriseproducts.com/index.asp $@
./initracer.js --site cisco.com --url http://www.cisco.com/c/en/us/index.html $@
./initracer.js --site sysco.com --url http://www.sysco.com/ $@
./initracer.js --site ingrammicro.com --url http://www.ingrammicro.com/IMD_WASWeb/jsp/login/corporate.jsp $@
./initracer.js --site us.coca-cola.com --url http://us.coca-cola.com/home/ $@
./initracer.js --site lockheedmartin.com --url http://www.lockheedmartin.com/ $@
./initracer.js --site fedex.com --url http://www.fedex.com/us/ $@
./initracer.js --site johnsoncontrols.com --url http://www.johnsoncontrols.com/ $@
./initracer.js --site ir.pagp.com --url http://ir.pagp.com/ $@
./initracer.js --site wfscorp.com --url https://www.wfscorp.com/ $@
./initracer.js --site chsinc.com --url http://www.chsinc.com/ $@
./initracer.js --site aa.com --url https://www.aa.com/homePage.do $@
./initracer.js --site merck.com --url http://www.merck.com/index.html $@
./initracer.js --site bestbuy.com --url http://www.bestbuy.com/?intl=nosplash $@
./initracer.js --site delta.com --url http://www.delta.com/ $@
./initracer.js --site honeywell.com --url http://honeywell.com/Pages/Home.aspx $@
./initracer.js --site hcahealthcare.com --url http://www.hcahealthcare.co.uk/ $@
./initracer.js --site goldmansachs.com --url http://www.goldmansachs.com/ $@
./initracer.js --site tsocorp.com --url http://tsocorp.com/ $@
./initracer.js --site libertymutual.com --url https://www.libertymutual.com/ $@
./initracer.js --site united.com --url https://www.united.com/ual/en/us/ $@
./initracer.js --site newyorklife.com --url https://www.newyorklife.com/ $@
./initracer.js --site oracle.com --url http://www.oracle.com/index.html $@
./initracer.js --site morganstanley.com --url http://www.morganstanley.com/ $@
./initracer.js --site tysonfoods.com --url http://www.tysonfoods.com/ $@
./initracer.js --site safeway.com --url http://www.safeway.com/ $@
./initracer.js --site nationwide.com --url https://www.nationwide.com/ $@
./initracer.js --site deere.com --url https://www.deere.com/en_US/regional_home.page $@
./initracer.js --site dupont.com --url http://www.dupont.com/ $@
./initracer.js --site americanexpress.com --url https://www.americanexpress.com/ $@
./initracer.js --site allstate.com --url https://www.allstate.com/ $@
./initracer.js --site cigna.com --url http://www.cigna.com/ $@
./initracer.js --site mondelezinternational.com --url http://www.mondelezinternational.com/ $@
./initracer.js --site tiaa.org --url https://www.tiaa.org/public/index.html $@
./initracer.js --site intlfcstone.com --url https://www.intlfcstone.com/ $@
./initracer.js --site massmutual.com --url https://www.massmutual.com/ $@
./initracer.js --site directv.com --url http://www.directv.com/ $@
./initracer.js --site halliburton.com --url http://www.halliburton.com/en-US/default.page $@
./initracer.js --site 21cf.com --url http://www.21cf.com/ $@
./initracer.js --site 3m.com --url http://www.3m.com/3M/en_US/company-us/ $@
./initracer.js --site searsholdings.com --url https://searsholdings.com/ $@
./initracer.js --site generaldynamics.com --url http://www.generaldynamics.com/ $@
