./initracer.js --site test-access-before-definition --url http://localhost:8080/test/access-before-definition/dropdown/index.html $@
./initracer.js --site test-access-before-definition-deterministic --url http://localhost:8080/test/access-before-definition/deterministic/index.html $@
./initracer.js --site test-late-event-handler-registration-1 --url http://localhost:8080/test/late-event-handler-registration/dropdown/index.html $@
./initracer.js --site test-late-event-handler-registration-2 --url http://localhost:8080/test/late-event-handler-registration/inline-after-external-script/index.html $@
./initracer.js --site test-form-input-overwritten-checkbox --url http://localhost:8080/test/form-input-overwritten/checkbox/index.html $@
./initracer.js --site test-form-input-overwritten-dropdown --url http://localhost:8080/test/form-input-overwritten/dropdown/index.html $@
./initracer.js --site test-form-input-overwritten-radio --url http://localhost:8080/test/form-input-overwritten/radio/index.html $@
./initracer.js --site test-form-input-overwritten-text-field --url http://localhost:8080/test/form-input-overwritten/text-field/index.html $@
./initracer.js --site test-form-input-overwritten-text-focus-harmful --url http://localhost:8080/test/form-input-overwritten/focus-harmful/index.html $@
./initracer.js --site test-form-input-overwritten-text-focus-harmful-html --url http://localhost:8080/test/form-input-overwritten/focus-harmful-html/index.html $@
./initracer.js --site test-form-input-overwritten-text-focus-harmless --url http://localhost:8080/test/form-input-overwritten/focus-harmless/index.html $@
