var _bind = Function.prototype.bind;

// A map from functions that have been generated by calling
// Function.prototype.bind, to their original function that
// was passed to bind().
var bindings = new Map();

/**
 * Replace bind() to keep track of the functions that have been
 * generated by calling bind.
 */
Function.prototype.bind = function () {
    var f = this;
    var g = _bind.apply(this, arguments);
    bindings.set(g, f);
    return g;
};

module.exports = bindings;
